version: '3.7'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports: 
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on: 
        - mongo

  api:
    image: node:alpine
    container_name: trepo_api
    restart: on-failure
    ports: 
      - "3000:3000"
    environment: 
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
    volumes: 
      - ./api:/app
    working_dir: /app
    depends_on:
      - mongo
    command: /bin/sh -c "npm install -g @nestjs/cli && npm install && npm run start:dev"