apiVersion: v1
kind: Service
metadata:
  name: hello-srv
  labels:
    app: hello
spec:
  ports:
  - name: hello
    port: 5000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  selector:
    name: hello
