apiVersion: v1
kind: Service
metadata:
  name: mc-users-srv
  labels:
    app: mc-users
spec:
  ports:
  - name: mc-users
    port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: mc-users
