apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-users
  template:
    metadata:
      labels:
        app: mc-users
    spec:
      containers:
        - name: mc-users
          image: atewan/mc-users:1.0.8
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_HOSTNAME
              value: "db-users-srv"